### ISSUE TITLE
事件詳細の手続段階は候補から選択するようにしたい

### ISSUE THREAD

**Issue by knykhsmt** [legalwinQ/front#28]
候補としては，以下のようになります

"訴外","訴訟（一審）","調停","審判","控訴審","抗告審","上告審","執行","保全"，"被疑者"，"被告人"

**Comment by kiyonori-matsumoto** [comment]
対応しました、

![image](https://user-images.githubusercontent.com/16646684/41247905-5eb2161e-6dea-11e8-92c9-664e5830c3ea.png)
