### ISSUE TITLE
画面上部の緑っぽい帯の色を#14bae2にしたい

### ISSUE THREAD

**Issue by knykhsmt** [legalwinQ/front#30]
どんな色がいいかとイメージをより明確にするために，サイトで使ってみるとどんな感じかが見てみたいです

**Comment by kiyonori-matsumoto** [comment]
@knykhsmt 

先程デプロイして、対応してみました。
こんな感じです。

![image](https://user-images.githubusercontent.com/16646684/41164483-37165622-6b76-11e8-9037-58d3fd43dc8b.png)

**Comment by knykhsmt** [comment]
@kiyonori-matsumoto 
ありがとうございます！
実際に画面に表示してみるとイメージがわかりますね！

ちょっとイメージと違う感じの色でしたね。。

**Comment by kiyonori-matsumoto** [comment]
了解です、またスタイルの要望があればお願いします！
