### ISSUE TITLE
事件一覧画面から，業務メモ一覧画面に行けるようにしたい

### ISSUE THREAD

**Issue by knykhsmt** [legalwinQ/front#31]
業務メモ一覧画面というのは，業務メモのみが表示されている画面で，その弁護士の全事件を縦断して新しい順に業務メモが並んでいる画面です。

例えば弁護士が外出から戻ってきたときなどに，この画面を見れば，自分の担当している事件についてどのような動きがあったかを時系列で串刺しにして確認することができるという画面です

**Comment by kiyonori-matsumoto** [comment]
メモ程度ですが。。。

- この一覧は、弁護士(≠事務員)が使う想定ですかね？  
  いまいま想定している仕様だと、「事件を所有している弁護士」の単位で業務メモが表示される、という仕様かなと思ってます。

弁護士1に事件A, Bがあるとして、事務員2 が事件Aの業務メモにコメントすると、弁護士1をインデックスにして業務メモの一覧表示が出来る、という仕様になるかと思いますが認識違い無いですか？

**Comment by knykhsmt** [comment]
ええと，想定としては，弁護士も事務員も使うことを想定してます。
弁護士なり，事務員なりがログインしたときに，そのユーザーがアクセスする権限のある事件すべてを対象として，時系列順に並んで表示させる，ということができればと思ってます

**Comment by kiyonori-matsumoto** [comment]
すいません、もう少し、、

以下のケースのときにそれぞれどの程度リストアップされているのが望ましいですかね？

1. 弁護士Aと事務員1が同じ事務所に所属している時、事務員1は弁護士Aの所有する事件に関してのメモの一覧を表示する
2. 弁護士A, Bと事務員1が同じ事務所に所属している時、事務員1は弁護士A, Bの所有する事件に関してのメモの一覧を表示する
3. 弁護士A, Bと事務員1が同じ事務所に所属している時、弁護士Aは弁護士A, Bの所有する事件に関してのメモの一覧を表示する

個人的に、1. 2. のケースはYes、3. のケースはNo(自身の事件に関してのメモのみ一覧表示したい)というのがユースケースかなと思っていました。

頂いた、「そのユーザーがアクセスする権限のある事件すべてを対象として，時系列順に並んで表示させる」の場合、1, 2, 3全てがYesとなってしまう点が気になっていますが、特に3. の場合も対して影響は無いですか？邪魔じゃないですかね？

**Comment by knykhsmt** [comment]
前に説明していただいたアカウントのあり方とも関連してきそうですね。

１，２についてはイエスで，３についてはノー（自身の事件に関してのみ一覧表示）というのは想定と一致してます。

ただ，３のケースでは，弁護士Aは弁護士Bの事件に当然にアクセスできるのではなくて（アクセスというか，弁護士Bの事件は弁護士Aの事件一覧のところに当然には表示されない），弁護士Bが関与弁護士のような形で弁護士Aのことを設定して初めてアクセスできる（ないし弁護士Aの事件一覧にも表示される）ということを想定していました。

・事件一覧で表示される事件と，業務メモ一覧でメモが表示される事件は同じ
・各弁護士は，原則自分の事件だけが事件一覧で表示される（業務メモ一覧で表示されるのは自分の事件だけ）
・関与弁護士の設定をされているものについては，人の事件でも事件一覧に表示される（し，業務メモ一覧にも表示される）
ということを前提とした，「そのユーザーがアクセスする権限がある事件（事件一覧に表示される事件）すべてを対象として時系列表示」という趣旨で言っていました
データベースの構造的に厳しいですか？

上の「事件一覧に表示される事件」は，事務員との関係でも同様のことを想定していました。
たとえば，事務員が一人であれば上の２のようになりますが，複数の弁護士と複数の事務員がいた場合には，異なることになりうるかなと思います。
つまり，一人の事務員は常に所属している弁護士全員の事件が事件一覧に表示されるという位置づけではなくて，担当事務員に設定されているものだけが事件一覧にも業務メモ一覧にも表示されるとしたいです。

４については，一人の弁護士が複数の事務所に同時に所属するということはないので（法律だったか日弁連の規則だったかで，一事務所にしか所属できないことになっています），事務所毎に分ける必要は特にないのかなと思います。

ちょっとややこしいですよね。
自分の考えていることがついていけてない可能性があるので，ご不明の点があったら確認していただければ。

**Comment by kiyonori-matsumoto** [comment]
ありがとうございます。事件と弁護士事務員の関連については理解しました。

担当に設定された場合のみ他社の事件にアクセスできる、という前提だとすると、以前お伺いした、
「雇われの事務員が弁護士の事件を作成できる」という要件とマッチしていないです。

ユーザー単位で共有設定ができて、その共有設定をするとすべての事件を共有できる、
また事件毎に共有設定ができて、共有設定をすると他の弁護士が事件を参照できる、って感じですかね？

ただターゲットとしている層を見ると、事件毎の共有はターゲット層の要求からは外れそうなので、そちらは優先度を落として対応すると思います。
（まずは弁護士１↔事務員複数のモデルからいきたいと思います）

上記仮定だとすると、
ユーザー単位で共有設定ができて、その共有設定をするとすべての事件を共有できる、に基づいて、
弁護士Aが事務員１に対して共有設定をONにすると、事務員１は弁護士Aの権限で事件を作成できる、
事務員１は自身の事件（空）と、弁護士Aの事件の一覧を表示できる、
という実装になりそうですが、、、

法律上で複数の事務所に同時に所属できないという話も初めて頂いたので、もう一回どこかで整理する場を設けたいなと思います。（今のモデルは複数事務所を持てる）

難しい…

**Comment by knykhsmt** [comment]
>担当に設定された場合のみ他社の事件にアクセスできる、という前提だとすると、以前お伺いした、
「雇われの事務員が弁護士の事件を作成できる」という要件とマッチしていないです。

なるほど。。

それ以降の話も優先度含め了解です。

なかなかうまく伝えられなくて申し訳ないです。。
またすり合わせをしたいですね。
近いうちに，打合せの日程調整をさせてもらいたいと思いますので，よろしくお願いします！
前回の打ち合わせ後にお伝えしていたように，事務所見学も兼ねて，うちの事務所で業務の点についても見ていただければと思います。
